package psimulator.dataLayer.Enums;

/**
 *
 * @author Martin
 */
public enum ObserverUpdateEventType {
    LANGUAGE,
    ICON_SIZE,
    SIMULATOR,
    SIMULATOR_PLAYER_LIST_MOVE,
    SIMULATOR_PLAYER_PLAY,
    SIMULATOR_PLAYER_STOP,
    //SIMULATOR_PLAYER_START,
    SIMULATOR_PLAYER_NEXT,
    SIMULATOR_SPEED,
    SIMULATOR_DETAILS,
    SIMULATOR_RECORDER,
    SIMULATOR_CONNECTION;
}
