/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package psimulator.userInterface.Simulator;

/**
 *
 * @author Martin Švihlík <svihlma1 at fit.cvut.cz>
 */
public class SimulatorControllPanel_Designer extends javax.swing.JPanel {

    /**
     * Creates new form SimulatorControllPanel_Designer
     */
    public SimulatorControllPanel_Designer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jSlider1 = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelPlayControls = new javax.swing.JPanel();
        jButtonFirst = new javax.swing.JButton();
        jButtonPrevious = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jButtonLast = new javax.swing.JButton();
        jSliderPlayerSpeed = new javax.swing.JSlider();
        jToggleButtonCapture = new javax.swing.JToggleButton();
        jLabelSpeedName = new javax.swing.JLabel();
        jToggleButtonPlay = new javax.swing.JToggleButton();
        jPanelEventList = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanelConnectSaveLoad = new javax.swing.JPanel();
        jButtonSaveListToFile = new javax.swing.JButton();
        jButtonLoadListFromFile = new javax.swing.JButton();
        jButtonConnectToServer = new javax.swing.JButton();
        jLabelConnectionStatusName = new javax.swing.JLabel();
        jLabelConnectionStatusValue = new javax.swing.JLabel();
        jPanelDetails = new javax.swing.JPanel();
        jCheckBoxPacketDetails = new javax.swing.JCheckBox();
        jCheckBoxNamesOfDevices = new javax.swing.JCheckBox();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setMaximumSize(new java.awt.Dimension(250, 300));
        setMinimumSize(new java.awt.Dimension(250, 300));

        jPanelPlayControls.setBorder(javax.swing.BorderFactory.createTitledBorder("Play controls"));

        jButtonFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/toolbarIcons/32/player_start.png"))); // NOI18N

        jButtonPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/toolbarIcons/32/player_rew.png"))); // NOI18N

        jButtonNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/toolbarIcons/32/player_fwd.png"))); // NOI18N

        jButtonLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/toolbarIcons/32/player_next.png"))); // NOI18N

        jSliderPlayerSpeed.setPaintTicks(true);
        jSliderPlayerSpeed.setToolTipText("Speed controll");

        jToggleButtonCapture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/toolbarIcons/32/Record Button.png"))); // NOI18N
        jToggleButtonCapture.setSelected(true);
        jToggleButtonCapture.setText("Capture");
        jToggleButtonCapture.setToolTipText("Capture packets from server");

        jLabelSpeedName.setText("Speed:");

        jToggleButtonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/toolbarIcons/32/player_play.png"))); // NOI18N
        jToggleButtonPlay.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/toolbarIcons/32/player_pause.png"))); // NOI18N
        jToggleButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPlayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPlayControlsLayout = new javax.swing.GroupLayout(jPanelPlayControls);
        jPanelPlayControls.setLayout(jPanelPlayControlsLayout);
        jPanelPlayControlsLayout.setHorizontalGroup(
            jPanelPlayControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPlayControlsLayout.createSequentialGroup()
                .addGroup(jPanelPlayControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPlayControlsLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabelSpeedName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderPlayerSpeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPlayControlsLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelPlayControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPlayControlsLayout.createSequentialGroup()
                                .addComponent(jButtonFirst)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPrevious)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButtonPlay)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonNext)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLast))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPlayControlsLayout.createSequentialGroup()
                                .addComponent(jToggleButtonCapture)
                                .addGap(126, 126, 126)))))
                .addContainerGap())
        );
        jPanelPlayControlsLayout.setVerticalGroup(
            jPanelPlayControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPlayControlsLayout.createSequentialGroup()
                .addGroup(jPanelPlayControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFirst)
                    .addComponent(jButtonPrevious)
                    .addComponent(jToggleButtonPlay)
                    .addComponent(jButtonNext)
                    .addComponent(jButtonLast))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPlayControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSliderPlayerSpeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSpeedName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jToggleButtonCapture))
        );

        jPanelEventList.setBorder(javax.swing.BorderFactory.createTitledBorder("Event list"));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelEventListLayout = new javax.swing.GroupLayout(jPanelEventList);
        jPanelEventList.setLayout(jPanelEventListLayout);
        jPanelEventListLayout.setHorizontalGroup(
            jPanelEventListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelEventListLayout.setVerticalGroup(
            jPanelEventListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelConnectSaveLoad.setBorder(javax.swing.BorderFactory.createTitledBorder("Connect / Save / Load "));

        jButtonSaveListToFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/toolbarIcons/32/filesave.png"))); // NOI18N
        jButtonSaveListToFile.setText("Save list to file");
        jButtonSaveListToFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSaveListToFile.setRequestFocusEnabled(false);
        jButtonSaveListToFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButtonLoadListFromFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/toolbarIcons/32/folder_blue_open.png"))); // NOI18N
        jButtonLoadListFromFile.setText("Load list from file");
        jButtonLoadListFromFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLoadListFromFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButtonConnectToServer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/toolbarIcons/32/kwifimanager.png"))); // NOI18N
        jButtonConnectToServer.setText("Connect to server");
        jButtonConnectToServer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonConnectToServer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabelConnectionStatusName.setText("Connection status:");

        jLabelConnectionStatusValue.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelConnectionStatusValue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/toolbarIcons/16/button_cancel.png"))); // NOI18N
        jLabelConnectionStatusValue.setText("Disconnected");

        javax.swing.GroupLayout jPanelConnectSaveLoadLayout = new javax.swing.GroupLayout(jPanelConnectSaveLoad);
        jPanelConnectSaveLoad.setLayout(jPanelConnectSaveLoadLayout);
        jPanelConnectSaveLoadLayout.setHorizontalGroup(
            jPanelConnectSaveLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConnectSaveLoadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConnectSaveLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConnectSaveLoadLayout.createSequentialGroup()
                        .addComponent(jLabelConnectionStatusName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelConnectionStatusValue)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelConnectSaveLoadLayout.createSequentialGroup()
                        .addComponent(jButtonConnectToServer, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLoadListFromFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSaveListToFile)))
                .addContainerGap())
        );
        jPanelConnectSaveLoadLayout.setVerticalGroup(
            jPanelConnectSaveLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConnectSaveLoadLayout.createSequentialGroup()
                .addGroup(jPanelConnectSaveLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonLoadListFromFile)
                    .addComponent(jButtonSaveListToFile)
                    .addComponent(jButtonConnectToServer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanelConnectSaveLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConnectionStatusName)
                    .addComponent(jLabelConnectionStatusValue)))
        );

        jPanelDetails.setBorder(javax.swing.BorderFactory.createTitledBorder("Details"));

        jCheckBoxPacketDetails.setText("Packet details");
        jCheckBoxPacketDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPacketDetailsActionPerformed(evt);
            }
        });

        jCheckBoxNamesOfDevices.setText("Names of devices");

        javax.swing.GroupLayout jPanelDetailsLayout = new javax.swing.GroupLayout(jPanelDetails);
        jPanelDetails.setLayout(jPanelDetailsLayout);
        jPanelDetailsLayout.setHorizontalGroup(
            jPanelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxPacketDetails)
                    .addComponent(jCheckBoxNamesOfDevices))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDetailsLayout.setVerticalGroup(
            jPanelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetailsLayout.createSequentialGroup()
                .addComponent(jCheckBoxPacketDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxNamesOfDevices)
                .addGap(0, 42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEventList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelConnectSaveLoad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelPlayControls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanelConnectSaveLoad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPlayControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelEventList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPlayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonPlayActionPerformed

    private void jCheckBoxPacketDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPacketDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxPacketDetailsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConnectToServer;
    private javax.swing.JButton jButtonFirst;
    private javax.swing.JButton jButtonLast;
    private javax.swing.JButton jButtonLoadListFromFile;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JButton jButtonSaveListToFile;
    private javax.swing.JCheckBox jCheckBoxNamesOfDevices;
    private javax.swing.JCheckBox jCheckBoxPacketDetails;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabelConnectionStatusName;
    private javax.swing.JLabel jLabelConnectionStatusValue;
    private javax.swing.JLabel jLabelSpeedName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelConnectSaveLoad;
    private javax.swing.JPanel jPanelDetails;
    private javax.swing.JPanel jPanelEventList;
    private javax.swing.JPanel jPanelPlayControls;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSliderPlayerSpeed;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JToggleButton jToggleButtonCapture;
    private javax.swing.JToggleButton jToggleButtonPlay;
    // End of variables declaration//GEN-END:variables
}
